[versions]
agp = "8.7.0"
kotlin = "2.0.20"
hilt = "2.52"
kotlinter = "4.4.1"
gradleVersions = "0.51.0"
firebase-googleServices = "4.4.2"
firebase-crashlytics = "3.0.2"
androidx-core = "1.13.1"
androidx-appcompat = "1.7.0"
androidx-recyclerView = "1.3.2"
androidx-constraintLayout = "2.1.4"
androidx-swipeRefreshLayout = "1.1.0"
androidx-fragment = "1.8.4"
androidx-preference = "1.2.1"
androidx-lifecycle-viewModel = "2.8.6"
compose-bom = "2024.09.03"
compose-navigation = "2.8.2"
compose-hilt = "1.2.0"
accompanist = "0.36.0"
material = "1.12.0"
coroutines = "1.9.0"
kotlinxSerialization = "1.7.3"
work-runtime = "2.9.1"
work-hilt = "1.2.0"
retrofit = "2.11.0"
okhttp = "4.12.0"
viewBindingPropertyDelegate = "1.5.9"
desugar = "2.1.2"
coil = "2.7.0"
firebase-bom = "33.4.0"
ksp = "2.0.20-1.0.25"
junit = "1.2.1"
espressoCore = "3.6.1"
uiautomator = "2.3.0"
baselineprofile = "1.3.2"
profileinstaller = "1.4.1"

[libraries]
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-recyclerView = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerView" }
androidx-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintLayout" }
androidx-swipeRefreshLayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidx-swipeRefreshLayout" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference" }
androidx-lifecycle-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewModel" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-toolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }

compose-materialIcons-core = { module = "androidx.compose.material:material-icons-core" }
compose-materialIcons-extended = { module = "androidx.compose.material:material-icons-extended" }

compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }

compose-hilt = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "compose-hilt" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

kotlinxSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime" }
work-hilt-core = { group = "androidx.hilt", name = "hilt-work", version.ref = "work-hilt" }
work-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "work-hilt" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }
retrofit-converter-kotlinxSerialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }

okhttp-doh = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttp" }

viewBindingPropertyDelegate-noReflection = { group = "com.github.kirich1409", name = "viewbindingpropertydelegate-noreflection", version.ref = "viewBindingPropertyDelegate" }

desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "baselineprofile" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersions" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

firebase-googleServices = { id = "com.google.gms.google-services", version.ref = "firebase-googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }

android-test = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
